server:
  port: 8080

spring:
  elasticsearch:
    jest:
      uris:
      - http://139.224.144.24:19200
      read-timeout: 60s
  gson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZ

  rabbitmq:
    host: 10.80.4.12
    port: 5672
    username: loansys
    password: loansys2018
    virtual-host: msgbus

zuul:
  retryable: true
  routes:
    home:
      path: /**
      url: forward:/

    credio-plus:
      path: /chain/**
      url: http://k8s-dlt.dev.chinacsci.com
  ignored-patterns:
  - /api/health/**


client:
  cloud-mirror: #云镜服务 个人征信
    url: https://api.xinyongyun.com
    apiKey: csci_pdd
    secretKey: nMuLHtb46oyb5uGznHIp
    appId: credit-cloud
  auth:
    url: http://auth-cc.dev.chinacsci.com
  cloud-mercury: #征信 企业服务.
    url: http://10.100.44.100/daas/api
    apiKey: d9e0ae9a-f2bd-4ebe-9404-c27801808fd6
    secretKey: 1fa29aba-5b56-4401-8900-984cb06458b4

feign:
  hystrix:
    enabled: true

spring.cloud.stream:

  bindings.api-record-input-channel.destination: com.csci.cloud.server.api-trace
  rabbit.bindings.api-record-input-channel.producer.routing-key-expression: '''api-trace.result'''

  bindings.api-record-output-channel.destination: com.csci.cloud.server.api-trace
  bindings.api-record-output-channel.group: api-trace.result
  rabbit.bindings.api-record-output-channel.consumer.bindingRoutingKey: api-trace.result


logging:
  config: classpath:logback-dev.xml
  file: ./logs/cloud-core.log

